# Generated by Django 3.0.2 on 2022-02-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('customer_fname', models.CharField(max_length=25)),
                ('customer_lname', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
